# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.1.0
group=com.cursee.peaceful_hunger
java_version=21

# Common
mod_name=Peaceful Hunger
mod_author=Jason13
mod_id=peaceful_hunger
license=Unlicense
credits=Thanks to Jaredlll08, Darkhax, Serilum, and PacifistMC.
description=Allows you to starve in Peaceful!

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.9-20250930.151910

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.9
parchment_version=2025.10.05

# Minecraft
minecraft_version=1.21.9
minecraft_version_range=[1.21.9, 1.22)

# Fabric
fabric_version=0.133.14+1.21.9
fabric_loader_version=0.17.2

# NeoForge
neoforge_version=21.9.9-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
